Fixes to some parsing logic. Add examples test. Update some project details

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -49,8 +49,25 @@ jobs:
       with:
         path: ${{ env.CACHE_PATHS }}
         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+
     - name: Run all tests
       run: cargo test --workspace --verbose --all-features
+      shell: bash
+
+    - name: Run some examples
+      shell: bash
+      continue-on-error: true
+      run: |
+        sites=(
+          "https://www.bbc.co.uk/news"
+          "https://en.wikipedia.org/wiki/Main_Page"
+          "https://github.com/"
+        )
+
+        for url in "${sites[@]}"; do
+          curl -sS $url > out.html
+          { cargo run --example main out.html --check } || echo "Could not parse source @ $url"
+        done
 
   clippy:
     needs: validity
